# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [2]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [3]:
sinasc_raw.shape

(27028, 69)

In [4]:
sinasc_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27028 entries, 0 to 27027
Data columns (total 69 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ORIGEM        27028 non-null  int64
 1   CODESTAB      26913 non-null  float64
 2   CODMUNNASC    27028 non-null  int64
 3   LOCNASC       27028 non-null  int64
 4   IDADEMAE      27028 non-null  int64
 5   ESTCIVMAE     26711 non-null  float64
 6   ESCMAE        26716 non-null  object
 7   CODOCUPMAE    24121 non-null  float64
 8   QTDFILVIVO    25455 non-null  float64
 9   QTDFILMORT    24930 non-null  float64
 10  CODMUNRES     27028 non-null  int64
 11  GESTACAO      25796 non-null  object
 12  GRAVIDEZ      26949 non-null  object
 13  PARTO         26979 non-null  object
 14  CONSULTAS     27028 non-null  int64
 15  DTNASC        27028 non-null  object
 16  HORANASC      27007 non-null  float64
 17  SEXO          27024 non-null  object
 18  APGAR1        26932 non-null  float64
 19  APGAR5        26925 non-null  float64
 20  RACACOR       26381 non-null  object
 21  PESO          27028 non-null  int64
 22  IDANOMAL      26437 non-null  float64
 23  DTCADASTRO    27028 non-null  object
 24  CODANOMAL     214 non-null    object
 25  NUMEROLOTE    27028 non-null  int64
 26  VERSAOSIST    27028 non-null  object
 27  DTRECEBIM     27028 non-null  object
 28  DIFDATA       27028 non-null  int64
 29  DTRECORIGA    0 non-null      float64
 30  NATURALMAE    26730 non-null  float64
 31  CODMUNNATU    26730 non-null  float64
 32  CODUFNATU     26730 non-null  float64
 33  ESCMAE2010    26779 non-null  float64
 34  SERIESCMAE    14318 non-null  float64
 35  DTNASCMAE     26988 non-null  float64
 36  RACACORMAE    26367 non-null  float64
 37  QTDGESTANT    25816 non-null  float64
 38  QTDPARTNOR    25149 non-null  float64
 39  QTDPARTCES    25237 non-null  float64
 40  IDADEPAI      7607 non-null   float64
 41  DTULTMENST    16956 non-null  float64
 42  SEMAGESTAC    25790 non-null  float64
 43  TPMETESTIM    25790 non-null  float64
 44  CONSPRENAT    26098 non-null  float64
 45  MESPRENAT     24161 non-null  float64
 46  TPAPRESENT    26763 non-null  float64
 47  STTRABPART    26081 non-null  float64
 48  STCESPARTO    26281 non-null  float64
 49  TPNASCASSI    26967 non-null  float64
 50  TPFUNCRESP    26961 non-null  float64
 51  TPDOCRESP     27014 non-null  float64
 52  DTDECLARAC    26976 non-null  float64
 53  ESCMAEAGR1    26779 non-null  float64
 54  STDNEPIDEM    27028 non-null  int64
 55  STDNNOVA      27028 non-null  int64
 56  CODPAISRES    27028 non-null  int64
 57  TPROBSON      27028 non-null  int64
 58  PARIDADE      27028 non-null  int64
 59  KOTELCHUCK    27028 non-null  int64
 60  CONTADOR      27028 non-null  int64
 61  munResStatus  27028 non-null  object
 62  munResTipo    27028 non-null  object
 63  munResNome    27028 non-null  object
 64  munResUf      27028 non-null  object
 65  munResLat     27027 non-null  float64
 66  munResLon     27027 non-null  float64
 67  munResAlt     27027 non-null  float64
 68  munResArea    27027 non-null  float64
dtypes: float64(38), int64(16), object(15)
memory usage: 14.2+ MB

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [5]:
sinasc_raw.groupby('munResNome')['IDADEMAE', 'IDADEPAI'].mean()

C:\Users\Artur\AppData\Local\Temp/ipykernel_13816/33997708.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  sinasc_raw.groupby('munResNome')['IDADEMAE', 'IDADEPAI'].mean()

                            IDADEMAE   IDADEPAI
munResNome
Alta Floresta D'Oeste      25.991826  29.548701
Alto Alegre dos Parecis    24.844156  29.179104
Alto Paraíso               24.960177  28.833333
Alvorada D'Oeste           25.770732  30.757282
Ariquemes                  25.607866  32.466667
Buritis                    25.559177  30.812500
Cabixi                     26.037500  34.333333
Cacaulândia                25.546667  36.333333
Cacoal                     26.890102  30.931854
Campo Novo de Rondônia     24.825301  30.500000
Candeias do Jamari         25.243323  29.894737
Castanheiras               27.281250  30.392857
Cerejeiras                 27.240506  31.652778
Chupinguaia                25.333333  29.629630
Colorado do Oeste          27.602804  34.354839
Corumbiara                 24.716535  32.470588
Costa Marques              24.412017  30.613636
Cujubim                    24.482927  31.400000
Espigão D'Oeste            26.093333  31.198113
Governador Jorge Teixeira  24.401786  29.222222
Guajará-Mirim              25.462228  30.470588
Itapuã do Oeste            26.064220  42.500000
Jaru                       25.982974  32.197183
Ji-Paraná                  26.361137  31.132239
Machadinho D'Oeste         25.480000  31.326923
Ministro Andreazza         27.904762  33.849315
Mirante da Serra           26.304878  32.154762
Monte Negro                25.648241  34.678571
Município ignorado - RO    24.000000  22.000000
Nova Brasilândia D'Oeste   26.222222  30.520833
Nova Mamoré                25.326389  31.692308
Nova União                 26.894231  31.371429
Novo Horizonte do Oeste    26.938776  31.588235
Ouro Preto do Oeste        26.375594  31.233244
Parecis                    26.454545  32.473684
Pimenta Bueno              25.199675  29.745174
Pimenteiras do Oeste       25.075000  35.600000
Porto Velho                26.312670  32.352679
Presidente Médici          25.796053  30.150754
Primavera de Rondônia      27.023256  31.888889
Rio Crespo                 26.660000  28.000000
Rolim de Moura             26.600863  30.360479
Santa Luzia D'Oeste        26.121212  30.703297
Seringueiras               24.910714  30.500000
São Felipe D'Oeste         26.481481  31.395833
São Francisco do Guaporé   25.660066  31.638889
São Miguel do Guaporé      25.926346  32.666667
Teixeirópolis              26.031250  31.500000
Theobroma                  25.536082  30.083333
Urupá                      26.688235  31.008929
Vale do Anari              26.096774  34.000000
Vale do Paraíso            25.679012  29.976744
Vilhena                    26.433962  34.152941

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [6]:
sinasc_raw[sinasc_raw['DTNASC'] == '2019-04-19']['SEXO'].value_counts()

Masculino    38
Feminino     32
Name: SEXO, dtype: int64

In [7]:
sinasc_raw[sinasc_raw['DTNASC'] == '2019-04-19'].groupby(['ESCMAE', 'SEXO'])['PESO'].mean().unstack()

SEXO                Feminino    Masculino
ESCMAE
1 a 3 anos       3782.000000          NaN
12 anos ou mais  3111.250000  3360.000000
4 a 7 anos       3295.625000  3365.625000
8 a 11 anos      3250.263158  3326.192308

### 3. Qual o municipio onde nasceram menos bebês em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [8]:
sinasc_raw['munResNome'].value_counts(ascending = True).head()

Município ignorado - RO     1
Castanheiras               32
Pimenteiras do Oeste       40
Primavera de Rondônia      43
Parecis                    44
Name: munResNome, dtype: int64

In [20]:
menos_bebes = sinasc_raw[sinasc_raw['munResNome'] == 'Castanheiras']
menos_bebes.groupby('munResNome').agg({'IDADEMAE': ['mean','max', 'min'], 
                                                                      'IDADEPAI': ['mean','max', 'min']})

              IDADEMAE           IDADEPAI
                  mean max min       mean   max   min
munResNome
Castanheiras  27.28125  39  17  30.392857  43.0  17.0

### 4. Qual o municipio onde nasceram mais bebês no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [41]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

In [21]:
sinasc_raw['munResNome'].value_counts(ascending = False).head()

Porto Velho    8437
Ji-Paraná      2182
Ariquemes      1729
Vilhena        1590
Cacoal         1374
Name: munResNome, dtype: int64

In [26]:
mais_bebes = sinasc_raw[sinasc_raw['munResNome'] == 'Porto Velho']
mais_bebes.groupby('munResNome').agg({'QTDFILVIVO': ['mean','max', 'min'], 
                                       'IDADEMAE': ['mean','max', 'min'], 
                                       'IDADEPAI': ['mean','max', 'min']})

            QTDFILVIVO             IDADEMAE           IDADEPAI
                  mean   max  min      mean max min       mean   max   min
munResNome
Porto Velho   1.167236  12.0  0.0  26.31267  47  12  32.352679  65.0  16.0

In [27]:
sinasc_raw.groupby('munResNome').agg({'QTDFILVIVO': ['mean','max', 'min'], 
                                       'IDADEMAE': ['mean','max', 'min'], 
                                       'IDADEPAI': ['mean','max', 'min']})

                          QTDFILVIVO              IDADEMAE           IDADEPAI  \
                                mean   max  min       mean max min       mean
munResNome
Alta Floresta D'Oeste       0.856354   7.0  0.0  25.991826  53  14  29.548701
Alto Alegre dos Parecis     0.907895   5.0  0.0  24.844156  41  14  29.179104
Alto Paraíso                1.162896   6.0  0.0  24.960177  42  11  28.833333
Alvorada D'Oeste            0.975248   9.0  0.0  25.770732  44  15  30.757282
Ariquemes                   0.962253   8.0  0.0  25.607866  44  13  32.466667
Buritis                     1.353846  10.0  0.0  25.559177  44  14  30.812500
Cabixi                      0.762500   4.0  0.0  26.037500  39  13  34.333333
Cacaulândia                 1.013333   7.0  0.0  25.546667  42  16  36.333333
Cacoal                      0.899123   7.0  0.0  26.890102  47  14  30.931854
Campo Novo de Rondônia      1.160305   5.0  0.0  24.825301  40  13  30.500000
Candeias do Jamari          1.433775   8.0  0.0  25.243323  45  14  29.894737
Castanheiras                1.062500   6.0  0.0  27.281250  39  17  30.392857
Cerejeiras                  0.987124   8.0  0.0  27.240506  53  15  31.652778
Chupinguaia                 1.081250   8.0  0.0  25.333333  42  13  29.629630
Colorado do Oeste           0.934579   8.0  0.0  27.602804  47  15  34.354839
Corumbiara                  0.849206   4.0  0.0  24.716535  43  15  32.470588
Costa Marques               1.258772  14.0  0.0  24.412017  41  12  30.613636
Cujubim                     1.256158   7.0  0.0  24.482927  42  14  31.400000
Espigão D'Oeste             1.405830  12.0  0.0  26.093333  44  14  31.198113
Governador Jorge Teixeira   0.768519   5.0  0.0  24.401786  41  13  29.222222
Guajará-Mirim               1.543563  11.0  0.0  25.462228  43  13  30.470588
Itapuã do Oeste             1.410000   6.0  0.0  26.064220  46  15  42.500000
Jaru                        0.891304   7.0  0.0  25.982974  45  12  32.197183
Ji-Paraná                   0.933272   8.0  0.0  26.361137  44  12  31.132239
Machadinho D'Oeste          1.114286  10.0  0.0  25.480000  44  13  31.326923
Ministro Andreazza          1.095238   6.0  0.0  27.904762  44  17  33.849315
Mirante da Serra            0.932515   5.0  0.0  26.304878  46  14  32.154762
Monte Negro                 0.989583   7.0  0.0  25.648241  40  14  34.678571
Município ignorado - RO     1.000000   1.0  1.0  24.000000  24  24  22.000000
Nova Brasilândia D'Oeste    0.879845   4.0  0.0  26.222222  51  15  30.520833
Nova Mamoré                 1.295455   8.0  0.0  25.326389  46  14  31.692308
Nova União                  0.844660   4.0  0.0  26.894231  39  16  31.371429
Novo Horizonte do Oeste     0.835052   4.0  0.0  26.938776  41  15  31.588235
Ouro Preto do Oeste         0.899361   6.0  0.0  26.375594  44  14  31.233244
Parecis                     1.302326   5.0  0.0  26.454545  41  16  32.473684
Pimenta Bueno               0.863934   9.0  0.0  25.199675  47  13  29.745174
Pimenteiras do Oeste        1.150000   5.0  0.0  25.075000  40  14  35.600000
Porto Velho                 1.167236  12.0  0.0  26.312670  47  12  32.352679
Presidente Médici           0.930233   7.0  0.0  25.796053  44  14  30.150754
Primavera de Rondônia       1.093023   4.0  0.0  27.023256  39  16  31.888889
Rio Crespo                  1.255319   4.0  0.0  26.660000  39  16  28.000000
Rolim de Moura              0.858542   5.0  0.0  26.600863  44  14  30.360479
Santa Luzia D'Oeste         1.171717  30.0  0.0  26.121212  41  15  30.703297
Seringueiras                0.880240   5.0  0.0  24.910714  42  14  30.500000
São Felipe D'Oeste          0.773585   5.0  0.0  26.481481  41  17  31.395833
São Francisco do Guaporé    1.079734   6.0  0.0  25.660066  41  14  31.638889
São Miguel do Guaporé       0.891117   6.0  0.0  25.926346  42  14  32.666667
Teixeirópolis               0.859375   6.0  0.0  26.031250  39  16  31.500000
Theobroma                   0.905263   4.0  0.0  25.536082  42  15  30.083333
Urupá                       0.946746   5.0  0.0  26.688235  43  15  31.008929
Vale do Anari               1.173913   8.0  0.0  26.096774  44  14  34.000000
Vale do Paraíso             0.696203   4.0  0.0  25.679012  52  14  29.976744
Vilhena                     0.917929  10.0  0.0  26.433962  46  14  34.152941


                            max   min
munResNome
Alta Floresta D'Oeste      58.0  17.0
Alto Alegre dos Parecis    50.0  16.0
Alto Paraíso               49.0  21.0
Alvorada D'Oeste           52.0  17.0
Ariquemes                  51.0  20.0
Buritis                    49.0  18.0
Cabixi                     47.0  19.0
Cacaulândia                50.0  28.0
Cacoal                     66.0  17.0
Campo Novo de Rondônia     40.0  21.0
Candeias do Jamari         41.0  21.0
Castanheiras               43.0  17.0
Cerejeiras                 52.0  19.0
Chupinguaia                46.0  20.0
Colorado do Oeste          53.0  23.0
Corumbiara                 52.0  21.0
Costa Marques              60.0  17.0
Cujubim                    44.0  19.0
Espigão D'Oeste            86.0  16.0
Governador Jorge Teixeira  37.0  22.0
Guajará-Mirim              44.0  19.0
Itapuã do Oeste            73.0  25.0
Jaru                       62.0  19.0
Ji-Paraná                  63.0  15.0
Machadinho D'Oeste         53.0  17.0
Ministro Andreazza         55.0  21.0
Mirante da Serra           56.0  20.0
Monte Negro                55.0  20.0
Município ignorado - RO    22.0  22.0
Nova Brasilândia D'Oeste   48.0  20.0
Nova Mamoré                43.0  19.0
Nova União                 53.0  18.0
Novo Horizonte do Oeste    56.0  20.0
Ouro Preto do Oeste        60.0  17.0
Parecis                    61.0  18.0
Pimenta Bueno              70.0  16.0
Pimenteiras do Oeste       45.0  25.0
Porto Velho                65.0  16.0
Presidente Médici          64.0  16.0
Primavera de Rondônia      44.0  21.0
Rio Crespo                 28.0  28.0
Rolim de Moura             69.0  16.0
Santa Luzia D'Oeste        53.0  18.0
Seringueiras               47.0  20.0
São Felipe D'Oeste         57.0  18.0
São Francisco do Guaporé   54.0  19.0
São Miguel do Guaporé      60.0  19.0
Teixeirópolis              67.0  20.0
Theobroma                  45.0  23.0
Urupá                      48.0  17.0
Vale do Anari              58.0  23.0
Vale do Paraíso            51.0  18.0
Vilhena                    60.0  18.0

In [33]:
sinasc_raw.groupby(['ESCMAE', 'SEXO'])['QTDFILVIVO', 'CONSULTAS', 'IDADEMAE', 'IDADEPAI'].mean().unstack()

C:\Users\Artur\AppData\Local\Temp/ipykernel_13816/703713465.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  sinasc_raw.groupby(['ESCMAE', 'SEXO'])['QTDFILVIVO', 'CONSULTAS', 'IDADEMAE', 'IDADEPAI'].mean().unstack()

                QTDFILVIVO           CONSULTAS             IDADEMAE  \
SEXO              Feminino Masculino  Feminino Masculino   Feminino
ESCMAE
1 a 3 anos        2.309417  2.470588  3.337662  3.350877  28.380952
12 anos ou mais   0.728577  0.718727  3.618253  3.628600  29.632812
4 a 7 anos        1.553704  1.554940  3.422026  3.443953  24.670044
8 a 11 anos       0.976596  0.952438  3.617716  3.618230  25.210086
Nenhuma           4.055556  3.363636  2.777778  3.409091  31.277778

                             IDADEPAI
SEXO             Masculino   Feminino  Masculino
ESCMAE
1 a 3 anos       28.470175  33.724138  33.860465
12 anos ou mais  29.467299  33.224910  32.694323
4 a 7 anos       24.547208  31.342975  30.936575
8 a 11 anos      25.092904  30.203791  29.854469
Nenhuma          31.818182  37.250000  41.000000

In [57]:
sinasc_raw.describe()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,CODMUNRES,...,STDNNOVA,CODPAISRES,TPROBSON,PARIDADE,KOTELCHUCK,CONTADOR,munResLat,munResLon,munResAlt,munResArea
count,27028.0,2.691300e+04,27028.000000,27028.000000,27028.000000,26711.000000,24121.000000,25455.000000,24930.000000,27028.000000,...,27028.000000,27028.0,27028.000000,27028.000000,27028.000000,2.702800e+04,27027.000000,27027.000000,27027.000000,27027.000000
mean,1.0,3.267629e+06,111037.796211,1.011396,26.093718,2.545318,795604.031591,1.053899,0.266506,110029.055720,...,0.999778,1.0,4.328437,0.648772,4.974952,7.367650e+05,-10.377988,-62.754987,179.111999,14702.799767
std,0.0,1.122677e+06,18102.751466,0.161679,6.387094,1.671248,283884.959287,1.170874,0.613909,36.036466,...,0.014898,0.0,2.930690,0.477363,2.067085,7.430325e+05,1.372942,1.269490,123.138365,13706.177751
min,1.0,1.531800e+04,110001.000000,1.000000,11.000000,1.000000,10205.000000,0.000000,0.000000,110000.000000,...,0.000000,1.0,1.000000,0.000000,1.000000,1.000000e+00,-13.499760,-65.329150,85.000000,459.978000
25%,1.0,2.496534e+06,110011.000000,1.000000,21.000000,1.000000,521125.000000,0.000000,0.000000,110012.000000,...,1.000000,1.0,2.000000,0.000000,4.000000,6.802750e+03,-11.433870,-63.831450,87.000000,3792.998000
50%,1.0,2.798484e+06,110020.000000,1.000000,26.000000,2.000000,999992.000000,1.000000,0.000000,110020.000000,...,1.000000,1.0,4.000000,1.000000,5.000000,1.364550e+04,-10.435950,-63.033270,153.000000,6896.648000
75%,1.0,3.970442e+06,110020.000000,1.000000,31.000000,5.000000,999992.000000,2.000000,0.000000,110028.000000,...,1.000000,1.0,5.000000,1.000000,5.000000,1.486846e+06,-8.768890,-61.945090,191.000000,34096.394000
max,1.0,9.659366e+06,520870.000000,4.000000,53.000000,9.000000,999994.000000,30.000000,28.000000,110180.000000,...,1.000000,1.0,11.000000,1.000000,9.000000,2.780269e+06,-8.768890,-60.138580,595.000000,34096.394000

In [58]:
maiores_cidades = sinasc_raw.query('munResArea >= 7000')
maiores_cidades.groupby(['munResNome', 'ESCMAE','munResArea']).agg({'QTDFILVIVO': ['count']})

                                                    QTDFILVIVO
                                                         count
munResNome               ESCMAE          munResArea
Alta Floresta D'Oeste    1 a 3 anos      7067.025           14
                         12 anos ou mais 7067.025           80
                         4 a 7 anos      7067.025           75
                         8 a 11 anos     7067.025          186
Guajará-Mirim            1 a 3 anos      24855.724          14
                         12 anos ou mais 24855.724          92
                         4 a 7 anos      24855.724         139
                         8 a 11 anos     24855.724         516
                         Nenhuma         24855.724           3
Machadinho D'Oeste       1 a 3 anos      8509.270           21
                         12 anos ou mais 8509.270           85
                         4 a 7 anos      8509.270          139
                         8 a 11 anos     8509.270          239
Nova Mamoré              1 a 3 anos      10071.643           7
                         12 anos ou mais 10071.643          27
                         4 a 7 anos      10071.643          85
                         8 a 11 anos     10071.643         274
                         Nenhuma         10071.643           2
Porto Velho              1 a 3 anos      34096.394         170
                         12 anos ou mais 34096.394        1680
                         4 a 7 anos      34096.394        1485
                         8 a 11 anos     34096.394        3833
                         Nenhuma         34096.394          13
São Francisco do Guaporé 1 a 3 anos      10959.767          11
                         12 anos ou mais 10959.767          42
                         4 a 7 anos      10959.767          46
                         8 a 11 anos     10959.767         200
São Miguel do Guaporé    1 a 3 anos      7460.219            4
                         12 anos ou mais 7460.219           62
                         4 a 7 anos      7460.219           58
                         8 a 11 anos     7460.219          222
                         Nenhuma         7460.219            2
Vilhena                  1 a 3 anos      11518.915          10
                         12 anos ou mais 11518.915         467
                         4 a 7 anos      11518.915         121
                         8 a 11 anos     11518.915         976
                         Nenhuma         11518.915           2

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Podemos concluir que quanto maior o grau de escolaridade dos pais, maior o número de variáveis que corroboram para saúde do filho, assim como a quantidade de filho é menor também. O mesmo ocorre para as cidades de menor área.